codecov:
  require_ci_to_pass: true

coverage:
  precision: 2
  round: down
  range: "60...80"
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: 85%
        threshold: 5%

ignore:
  - "**/*__data__*/*.ts"

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: false
