version: 1

# Files to include and exclude
include:
  - '**/*.ts'
  - '**/*.tsx'
  - '**/*.scss'
  - 'package.json'
  - '**/*.yaml'
  - '**/*.md'
  - '**/*.js'
  - '**/*.cjs'
  - '**/*.mjs'

exclude:
  - 'dist/**'
  - 'node_modules/**'
  - 'coverage/**'

rules:
  # ✅ Complexity
  complexity:
    maxFunctionLength: 60
    maxNestedBlocks: 3

  # ✅ Naming
  naming:
    enforcePascalCaseForComponents: true

  # ✅ TypeScript rules
  typescript:
    enforceStrictNullChecks: true
    preferReadonlyProps: true
    suggestBetterTypes: true

  # ✅ React rules
  react:
    enforceHooksRules: true
    preferFunctionComponents: true
    avoidInlineStyles: true

  # ✅ Performance
  performance:
    avoidUnnecessaryRerenders: true
    suggestMemoization: true

  # ✅ Architecture & Readability
  architecture:
    enforceSeparationOfConcerns: true
    suggestFolderStructure: true
    suggestCodeSplitting: true

# ✅ Keep professional and no poems
review_comments:
  tone: 'professional'
  detail: 'medium'
  style: 'formal'

limits:
  maxFileSizeKB: 500
  maxReviewTimeMinutes: 10
