# Yarn Berry configuration
# Using node-modules linker for compatibility with existing tooling
nodeLinker: node-modules

# Enable compression for the cache
compressionLevel: mixed

# Specify the default install state path
enableGlobalCache: false
