compressionLevel: mixed

enableGlobalCache: false

npmMinimalAgeGate: "7d"

httpProxy: "${HTTP_PROXY:-}"

httpsProxy: "${HTTPS_PROXY:-}"

nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.17.0.cjs

supportedArchitectures:
  os:
    - linux
    - darwin
  cpu:
    - x64
    - arm64
