FROM registry.access.redhat.com/ubi9/nodejs-20@sha256:938970e0012ddc784adda181ede5bc00a4dfda5e259ee4a57f67973720a565d1 as builder

WORKDIR  /opt/app-root/src
RUN npm install yarn --global

COPY @types @types
COPY public public
COPY src src
COPY package.json package.json
COPY tsconfig.json tsconfig.json
COPY webpack.config.js webpack.config.js
COPY webpack.prod.config.js webpack.prod.config.js 
COPY yarn.lock yarn.lock
COPY .swcrc .swcrc
COPY aliases.config.js aliases.config.js

################################## Sealights ##################################
COPY .git .git
USER root
ARG BSID AGENT_VERSION

ENV BSID=${BSID} \
    AGENT_VERSION=${AGENT_VERSION} \
    SEALIGHTS_TOKEN_FILE=/opt/app-root/src/sl-token \
    BUILD_DIR=dist \
    SL_BUILD_DIR=sl_dist \
    NODE_DEBUG=sl \
    SL_fileExtensions=".js,.jsx,.ts,.tsx"

RUN --mount=type=secret,id=sealights-credentials/token \
    cp /run/secrets/sealights-credentials/token $SEALIGHTS_TOKEN_FILE
RUN chown -R $(whoami) .
RUN chmod +r ${SEALIGHTS_TOKEN_FILE}
# Needed due to: https://sealights.atlassian.net/wiki/spaces/SUP/pages/1172144129/Javascript+and+Node.js+Source+Map+Files#No-Column-Information
RUN sed -i 's/"compilerOptions": {/"compilerOptions": {"sourceMap": true,/g' tsconfig.json
###############################################################################

RUN yarn install
RUN yarn build

################################## Sealights ##################################
RUN npm i -g "slnodejs@${AGENT_VERSION}"

RUN slnodejs scan \
    --buildsessionid ${BSID} \
    --scm git \
    --workspacepath ${BUILD_DIR} \
    --tokenfile ${SEALIGHTS_TOKEN_FILE} \
    --outputpath ${SL_BUILD_DIR} \
    --babylonPlugins "jsx,typescript" \
    --instrumentForBrowsers
###############################################################################

FROM registry.access.redhat.com/ubi9/nginx-120@sha256:c5fdf1b976571cf1f058b8f2dd955a94d80ced7a43756362d7e87d99e9c92337

ENV SL_BUILD_DIR=sl_dist NODE_DEBUG=sl
COPY --from=builder /opt/app-root/src/${SL_BUILD_DIR}/* /opt/app-root/src/

USER 0
# Disable IPv6 since it's not enabled on all systems
RUN sed -i '/\s*listen\s*\[::\]:8080 default_server;/d' /etc/nginx/nginx.conf
USER 1001

CMD ["nginx", "-g", "daemon off;"]
