---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: periodic-jobs-role
  namespace: konflux-ui-tenant
rules:
  - verbs:
      - get
      - watch
      - list
      - update
      - patch
    apiGroups:
      - appstudio.redhat.com
    resources:
      - snapshots
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: periodic-jobs-rolebinding
  namespace: konflux-ui-tenant
subjects:
  - kind: ServiceAccount
    name: konflux-ui-tenant
    namespace:
roleRef:
  kind: Role
  name: periodic-jobs-role
  apiGroup: rbac.authorization.k8s.io
---