import { pageHeaderPO } from '../pageObjects/pageHeader-po';

export enum Themes {
  LIGHT = 'light',
  DARK = 'dark',
  SYSTEM = 'system',
}

export class ThemeSwitcher {
  static clickThemeSwitcher() {
    cy.get(pageHeaderPO.themeDropdownToggle).should('be.visible').click();
    cy.get(pageHeaderPO.themeDropdown).should('be.visible');
  }

  static switchTheme(from: Themes, to: Themes) {
    cy.get(pageHeaderPO.themeOption(to)).click();

    // The page theme changed to the selected theme.
    cy.get(pageHeaderPO.htmlTheme).should('not.have.class', `pf-v6-theme-${from}`);

    // Selectors are at the correct row.
    cy.get(pageHeaderPO.themeOptionButton(from)).should('not.have.class', pageHeaderPO.selected);
    cy.get(pageHeaderPO.themeOptionButton(to)).should('have.class', pageHeaderPO.selected);
  }
}

export enum Contrasts {
  DEFAULT = 'default',
  HIGH = 'high',
  SYSTEM = 'system',
}

export class ContrastSwitcher {
  static switchContrast(from: Contrasts, to: Contrasts) {
    cy.get(pageHeaderPO.contrastOption(to)).click();

    // The page contrast changed to the selected contrast.
    cy.get(pageHeaderPO.htmlTheme).should('not.have.class', `pf-v6-theme-${from}-contrast`);

    // Selectors are at the correct row.
    cy.get(pageHeaderPO.contrastOptionButton(from)).should('not.have.class', pageHeaderPO.selected);
    cy.get(pageHeaderPO.contrastOptionButton(to)).should('have.class', pageHeaderPO.selected);
  }
}

// Generated by Cypress Author on 2026-09-23
enum HelpMenuItem {
  ABOUT = 'about',
  CLI_LOGIN = 'cli-login',
  DOCUMENTATION = 'documentation',
  FEEDBACK = 'feedback',
}

export class HelpMenu {
  // Label displayed for each expected Help menu item, keyed by its `data-test` suffix.
  static readonly items: Record<HelpMenuItem, string> = {
    [HelpMenuItem.ABOUT]: 'About Konflux',
    [HelpMenuItem.CLI_LOGIN]: 'Copy login command',
    [HelpMenuItem.DOCUMENTATION]: 'Documentation',
    [HelpMenuItem.FEEDBACK]: 'Share feedback',
  };

  static clickHelpMenuToggle() {
    cy.get(pageHeaderPO.helpMenuToggle).should('be.visible').click();
    cy.get(pageHeaderPO.helpMenu).should('be.visible');
  }

  static verifyMenuItems() {
    const expectedItems = Object.values(HelpMenuItem);

    // Exactly the expected items are rendered in the menu - no more, no less.
    cy.get(pageHeaderPO.helpMenu)
      .find('li[data-test^="help-dropdown-"]')
      .should('have.length', expectedItems.length);

    expectedItems.forEach((item) => {
      cy.get(pageHeaderPO.helpMenuItem(item))
        .should('be.visible')
        .and('contain.text', HelpMenu.items[item]);
    });
  }

  static verifyDocumentationLink(url: string) {
    cy.get(pageHeaderPO.helpMenuItem(HelpMenuItem.DOCUMENTATION))
      .find('a')
      .should('have.attr', 'href', url)
      .and('have.attr', 'target', '_blank')
      .and('have.attr', 'rel', 'noopener noreferrer');
  }

  static closeHelpMenu() {
    cy.get(pageHeaderPO.helpMenuToggle).click();
    cy.get(pageHeaderPO.helpMenu).should('not.exist');
  }
}
