name: 'Run Konflux UI E2E tests'
description: 'Executes E2E tests for Konflux UI using Cypress'

runs:
  using: "composite"
  steps:
    - name: Run Konflux UI E2E tests
      run: |
        : Run Konflux UI E2E tests
        ./pr_check.sh test
      shell: bash