name: 'Run Konflux UI E2E tests'
description: 'Executes E2E tests for Konflux UI using Cypress'

runs:
  using: "composite"
  steps:
    - name: Run Konflux UI E2E tests
      id: e2e
      run: |
        : Run Konflux UI E2E tests
        if [[ ${{ env.JOB_TYPE }} == 'periodic-stage' ]]; then
          echo "Running test suite against stage backend..."
          ./pr_check.sh test-stage
        else
          echo "Running test suite against local Konflux UI and backend"
          ./pr_check.sh test
        fi
      shell: bash

    - name: Report job result to Slack
      if: ${{ always() }}
      run: |
        if [[ ${{ env.JOB_TYPE }} == 'periodic'* ]]; then
          ./pr_check.sh send-report ${{ steps.e2e.outcome }}
        fi
      shell: bash