on:
  pull_request:
    types: [opened, synchronize, reopened]
  issue_comment:
    types: [created, edited]

jobs:
  check-coderabbit-resolved:
    runs-on: ubuntu-latest
    steps:
      - name: Check for unresolved CodeRabbit comments
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -euo pipefail
          gh auth status
          PR_NUMBER=${{ github.event.pull_request.number }}
          OWNER=${{ github.repository_owner }}
          REPO=${{ github.event.repository.name }}

          echo "Checking unresolved CodeRabbit comments for PR #$PR_NUMBER"

          COMMENTS=$(gh api repos/$OWNER/$REPO/pulls/$PR_NUMBER/comments --paginate \
            --jq '[ (if . == null then [] else . end)[] | select(.user.login == "coderabbit-ai[bot]") ]')

          if [ "$COMMENTS" = "[]" ]; then
            echo "✅ No CodeRabbit comments found."
            exit 0
          fi

          UNRESOLVED=$(gh api repos/$OWNER/$REPO/pulls/$PR_NUMBER/comments -paginate \
            --jq '[.[] | select((.resolved == false) and any(.comments[]; .user.login == "coderabbit-ai[bot]"))]')
          if [ "$UNRESOLVED" != "[]" ]; then
            echo "❌ There are unresolved CodeRabbit comments. Please resolve them before merging."
            exit 1
          fi

          echo "✅ All CodeRabbit comments resolved."
