name: Release Automation

on:
  schedule:
    - cron: '0 10 * * *'  # Daily for staging
    - cron: '0 10 */14 * *'  # Bi-weekly for production
  workflow_dispatch:
    inputs:
      target_branch:
        description: 'Target branch to deploy'
        required: true
        default: 'staging'
        type: choice
        options:
          - staging
          - production

jobs:
  create-release-mr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install deps & run release script
        env:
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          TARGET_BRANCH=${{ github.event.inputs.target_branch || 'staging' }}
          node .github/scripts/create-release-mr.js $TARGET_BRANCH

